name: cake
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cake_store.png
    - assets/images/Star.png
    - assets/images/chevron-right.png
    - assets/images/profileimage.png
    - assets/images/tkdtpwnthdkdlzhs.png
    - assets/images/hearticon.png
    - assets/images/caketwo.jpeg.webp
    - assets/images/cakethree.jpg
    - assets/images/cakeone.png